import Foundation
import SwiftData

/// Core book metadata — ported from backend `Book`.
/// IDs are UUID strings (sync-friendly). JSON arrays are stored as `[String]`.
@Model
final class Book {
    // No @Attribute(.unique): CloudKit stores don't support unique constraints.
    // IDs are UUIDs generated by the app, which keeps them unique in practice.
    var id: String = UUID().uuidString
    var title: String = ""
    var authors: [String] = []
    var isbn: String?
    var publicationYear: Int?
    /// Arbitrary user/AI-assigned labels (the shelf-organization input; a tag
    /// is not a controlled vocabulary). Stored under `genres` because SwiftData
    /// cannot rename stored properties in CloudKit-backed stores — so the
    /// Swift API is `tags` (below) while the persistent field keeps its legacy
    /// name. No migration is needed.
    var genres: [String] = []
    /// Fiction / non-fiction classification. Values: `""` (not set),
    /// `fiction`, `non-fiction`. Set by the user or proposed by the AI shelf
    /// pass; it is the top-level partition of the two-tier shelf grouping.
    var kind: String = ""
    /// Manual shelf assignments — a user-curated shelf name, not an AI
    /// taxonomy. Multi-select; managed without AI.
    var shelves: [String] = []
    var coverImageURL: String?
    var publisher: String?
    var pageCount: Int?
    var bookDescription: String?
    var descriptionSource: String?  // openlibrary | googlebooks | wikipedia | none
    /// Open Library work key (e.g. "/works/OL45804W") captured when the book
    /// was looked up in the catalog. Enables direct /works/{key}.json
    /// description fetches instead of fuzzy title+author re-search. Never
    /// user-editable; purely an internal enrichment key.
    var olKey: String?
    var language: String?
    var physicalLocation: String?
    var status: String = "to-read"  // reading | to-read | completed | donated
    var acquiredDate: Date?
    var purchasePrice: Double?
    var rating: Int?  // 1–5 stars
    var loanedTo: String?
    var loanedDate: Date?

    // Ownership for multi-user / family support
    var ownerID: String?
    var sharedLibraryID: String?
    var isPersonal: Bool = true

    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    // Sync metadata
    var syncState: String = "modified"  // synced | modified | deleted (tombstone)
    var syncUpdatedAt: Date = Date(timeIntervalSinceReferenceDate: 0)
    var syncDeviceID: String = ""

    // Relationships (optional: required for CloudKit-backed stores).
    @Relationship(deleteRule: .cascade, inverse: \Note.book)
    var notes: [Note]?

    @Relationship(inverse: \ReadingListItem.book)
    var listItems: [ReadingListItem]?

    @Relationship(deleteRule: .nullify, inverse: \Connection.book1)
    var connectionsAsBook1: [Connection]?

    @Relationship(deleteRule: .nullify, inverse: \Connection.book2)
    var connectionsAsBook2: [Connection]?

    init(
        id: String = UUID().uuidString,
        title: String,
        authors: [String] = [],
        isbn: String? = nil,
        publicationYear: Int? = nil,
        tags: [String] = [],
        kind: String = "",
        coverImageURL: String? = nil,
        publisher: String? = nil,
        pageCount: Int? = nil,
        bookDescription: String? = nil,
        descriptionSource: String? = nil,
        olKey: String? = nil,
        language: String? = nil,
        physicalLocation: String? = nil,
        status: String = "to-read",
        acquiredDate: Date? = nil,
        purchasePrice: Double? = nil,
        rating: Int? = nil,
        loanedTo: String? = nil,
        loanedDate: Date? = nil,
        ownerID: String? = nil,
        sharedLibraryID: String? = nil,
        isPersonal: Bool = true,
        createdAt: Date = Date(),
        updatedAt: Date = Date(),
        syncState: String = "modified",
        syncUpdatedAt: Date = Date(timeIntervalSinceReferenceDate: 0),
        syncDeviceID: String = "",
        shelves: [String] = []
    ) {
        self.id = id
        self.title = title
        self.authors = authors
        self.isbn = isbn
        self.publicationYear = publicationYear
        self.tags = tags
        self.kind = kind
        self.coverImageURL = coverImageURL
        self.publisher = publisher
        self.bookDescription = bookDescription
        self.descriptionSource = descriptionSource
        self.olKey = olKey
        self.language = language
        self.physicalLocation = physicalLocation
        self.status = status
        self.acquiredDate = acquiredDate
        self.purchasePrice = purchasePrice
        self.rating = rating
        self.loanedTo = loanedTo
        self.loanedDate = loanedDate
        self.ownerID = ownerID
        self.sharedLibraryID = sharedLibraryID
        self.isPersonal = isPersonal
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.syncState = syncState
        self.syncUpdatedAt = syncUpdatedAt
        self.syncDeviceID = syncDeviceID
        self.shelves = shelves
        self.notes = []
        self.listItems = []
        self.connectionsAsBook1 = []
        self.connectionsAsBook2 = []
    }
}

extension Book {
    /// App-wide name for the stored labels. `genres` is the CloudKit-safe
    /// persistent field (SwiftData can't rename in CloudKit stores), so `tags`
    /// is the canonical Swift spelling — reads/writes go through it everywhere.
    var tags: [String] {
        get { genres }
        set { genres = newValue }
    }

    /// Display authors joined by ", ".
    var authorsText: String {
        authors.isEmpty ? "Unknown" : authors.joined(separator: ", ")
    }

    /// Whether this book is currently loaned out.
    var isLoaned: Bool {
        loanedTo != nil && !(loanedTo?.isEmpty ?? true)
    }

    /// Reading status stored as `status` string.
    var statusEnum: BookStatus {
        BookStatus(rawValue: status) ?? .toRead
    }

    /// Canonical ISBN used for duplicate detection: digits only, always 13
    /// digits. Strips dashes/spaces, then upgrades a 10-digit ISBN-10 (last
    /// digit may be `X`) to its ISBN-13 equivalent so the same book scanned,
    /// typed, and looked up normalizes to one key. `nil` when nothing usable
    /// remains.
    static func normalizedISBN(_ raw: String?) -> String? {
        guard let raw else { return nil }
        let cleaned = raw
            .replacingOccurrences(of: "-", with: "")
            .replacingOccurrences(of: " ", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        if cleaned.count == 10 {
            return isbn10To13(cleaned)
        }
        return cleaned.isEmpty ? nil : cleaned
    }

    /// Converts an ISBN-10 to ISBN-13: prefix "978", keep the first nine
    /// digits (the tenth may be X), then recompute the check digit with the
    /// alternating 1/3 weights. A malformed ISBN-10 still converts — this
    /// feeds dedupe, not validation, so tolerance beats rejection.
    private static func isbn10To13(_ isbn10: String) -> String? {
        let digits = Array(isbn10.utf8)
        guard digits.dropLast().allSatisfy({ $0 >= 48 && $0 <= 57 }) else { return nil }
        let last = digits[9]
        guard last >= 48 && last <= 57 || last == 88 || last == 120 else { return nil }
        let first9 = isbn10.prefix(9)
        var sum = 0
        // Weights run across the FULL 12-digit stem ("978" + first9), left to
        // right alternating 1, 3 — the prefix contributes 9·1+7·3+8·1 = 38.
        for (i, c) in ("978" + first9).enumerated() {
            sum += Int(c.asciiValue! - 48) * (i % 2 == 0 ? 1 : 3)
        }
        let check = (10 - sum % 10) % 10
        return "978" + first9 + String(check)
    }
}

/// Fiction / non-fiction classification of a book. Stored on the Book; set by
/// the user when adding/editing or proposed by the AI shelf pass. `""` means
/// not yet set and routes the book to the "Uncategorized" top group.
enum BookKind: String, CaseIterable, Identifiable {
    case fiction = "fiction"
    case nonFiction = "non-fiction"
    case notSet = ""

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .fiction: return "Fiction"
        case .nonFiction: return "Non-fiction"
        case .notSet: return "Not set"
        }
    }
}

/// Book status enum mirroring backend `BookStatus`.
enum BookStatus: String, Codable, CaseIterable, Identifiable {
    case reading = "reading"
    case toRead = "to-read"
    case completed = "completed"
    case donated = "donated"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .reading: return "Reading"
        case .toRead: return "To read"
        case .completed: return "Completed"
        case .donated: return "Donated"
        }
    }

    init?(raw: String) {
        self.init(rawValue: raw)
    }
}
